package com.itechart.retailers.controller.constant;

public class Message {
	public static final String ITEM_NOT_FOUND_MSG = "Item is not found!";
	public static final String INCORRECT_ITEM_AMOUNT_INPUT_MSG = "Amount to dispatch cannot be more than actual amount";
	public static final String APPLICATION_CREATED_MSG = "Application created.";
	public static final String SUCCESS_DISPATCH_MSG = "Items dispatched successfully.";
	public static final String APPLICATION_ACCEPTED_MSG = "Application accepted.";
	public static final String NO_SPACE_IN_LOCATION_MSG = "There is no space in location!";
	public static final String LOCATION_IS_NOT_FOUND_MSG = "Location is not found.";
	public static final String SUCCESS_FORWARD_MSG = "Application forwarded.";
	public static final String BILL_CREATED_MSG = "Bill created.";
	public static final String ITEM_ADDED_MSG = "Item added.";
	public static final String LOCATION_ADDED_MSG = "Location added.";
	public static final String LOCATION_DELETED_MSG = "Location deleted.";
	public static final String INCORRECT_CURRENT_PASSWORD_MSG = "Incorrect current password!";
	public static final String EMPTY_PASSWORD_MSG = "New password cannot be empty!";
	public static final String PROFILE_UPDATED_MSG = "Profile updated.";
	public static final String SUPPLIER_CREATED_MSG = "Supplier created.";
	public static final String STATUS_UPDATED_MSG = "Status updated.";
	public static final String EMAIL_TAKEN_MSG = "Error: Email is already taken!";
	public static final String CUSTOMER_REGISTERED_MSG = "Customer registered successfully!";
	public static final String TAXES_UPDATED_MSG = "Taxes updated.";
	public static final String NEGATIVE_TAX_MSG = "Tax must not be negative";
	public static final String USER_ROLE_NOT_APPLICABLE_TO_LOCATION_MSG = "Selected user role can not be applied to selected location.";
	public static final String USER_CREATED_MSG = "User created.";
	public static final String STATUSES_UPDATED_MSG = "Statuses updated.";
	public static final String WRITE_OFF_ACT_CREATED_MSG = "Write-off act created.";
	public static final String INCORRECT_EMAIL_OR_PASSWORD_MSG = "Incorrect email or password!";
	public static final String TAXES_NOT_DEFINED_MSG = "Taxes for your items are not defined. Please, contact your director.";
	public static final String DISPATCH_ITEM_EXCEPTION_MSG = "You cannot dispatch zero items.";
	public static final String CUSTOMER_CATEGORY_MSG = "There is no such category in this customer menu.";
	public static final String APPLICATION_NOT_FOUND_MSG = "There is no application with this number.";
	public static final String BILL_ITEM_AMOUNT_EXCEPTION_MSG = "Item amount to sell cannot be greater than actual amount in shop!";
	public static final String LOCATION_IDENTIFIER_EXISTS_MSG = "Location with this identified already exists.";
	public static final String ROLE_NOT_FOUND_MSG = "Role is not found.";
	public static final String ITEM_ALREADY_EXISTS_MSG = "Item with this UPC already exists";
	public static final String APPLICATION_ALREADY_EXISTS_MSG = "Application with this number already exists.";
	public static final String BILL_ALREADY_EXISTS_MSG = "Bill with this number already exists";
	public static final String WRITE_OFF_ACT_ALREADY_EXISTS_MSG = "Write-off act with this identifier already exists";
}
